version: 2

chem:
  fp_option:
    type: morgan
    morgan_radius: 2
    morgan_n_bits: 256
  rxn_matrix: data/processed/split/matrix_train.pkl
  fpindex: data/processed/all/fpindex.pkl

data:
  init_stack_weighted_ratio: 0.90

model:
  encoder_type: graph
  encoder:
    num_atom_classes: 100
    num_bond_classes: 10
    dim: 512
    depth: 8
    dim_head: 64
    edge_dim: 128
    heads: 8
    rel_pos_emb: false
    output_norm: false
  
  decoder:
    d_model: 512
    nhead: 8
    dim_feedforward: 2048
    num_layers: 6
    pe_max_len: 32
    output_norm: false
    fingerprint_dim: ${chem.fp_option.morgan_n_bits}
    dim_fp_embed_hidden: 256
    num_reaction_classes: 100

  token_head:
    dim_hidden: 512
  reaction_head:
    num_reaction_classes: 100
    dim_hidden: 512
  fingerprint_head:
    d_model: 512
    num_out_fingerprints: 4
    fingerprint_dim: ${chem.fp_option.morgan_n_bits}
    dim_hidden: 512
    warmup_prob: 0.01

train:
  loss_weights:
    token: 1.0
    reaction: 1.0
    fingerprint: 0.5
  max_iters: 500_000
  val_freq: 5000
  max_grad_norm: 100.0
  optimizer:
    type: adamw
    lr: 3.e-4
    weight_decay: 0
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 5
    min_lr: 1.e-5
